
name: Conan cache restore

inputs:
  key:
    description: 'Key for the cache'
    required: true

outputs:
  cache-hit:
    description: 'Indictaes if the cache hit or not'
    value: ${{ steps.cache-conan.outputs.cache-hit }}
  cache-primary-key:
    description: 'The cache key'
    value: ${{ steps.cache-conan.outputs.cache-primary-key }}

runs:
  using: 'composite'
  steps:
  - name: cache/restore action
    id: cache-conan
    uses: actions/cache/restore@v3
    with:
      path: ./conan_cache.tgz
      key: ${{ inputs.key }}

  - name: conan cache restore
    if: ${{ steps.cache-conan.outputs.cache-hit }}
    shell: bash
    run: conan cache restore conan_cache.tgz
