
name: Run tests

inputs:
  compiler:
    description: 'msvc/gcc/clang/apple-clang'
    required: true

runs:
  using: 'composite'
  steps:
  - name: Setup build options (Linux)
    if: ${{ runner.os == 'Linux' }}
    shell: bash
    run: |
      echo "BUILD_TYPE=Release" >> $GITHUB_ENV
      echo "CMAKE_CONFIG_PRESET=conan-release" >> $GITHUB_ENV
      echo "CMAKE_BUILD_PRESET=conan-release" >> $GITHUB_ENV
      echo "CMAKE_TEST_PRESET=conan-release" >> $GITHUB_ENV

  - name: Setup build options (Windows)
    if: ${{ runner.os == 'Windows' }}
    shell: bash
    run: |
      echo "BUILD_TYPE=Release" >> $GITHUB_ENV
      echo "CMAKE_CONFIG_PRESET=conan-default" >> $GITHUB_ENV
      echo "CMAKE_BUILD_PRESET=conan-release" >> $GITHUB_ENV
      echo "CMAKE_TEST_PRESET=conan-release" >> $GITHUB_ENV

  - name: Setup build options (macOS)
    if: ${{ runner.os == 'macOS' }}
    shell: bash
    run: |
      echo "BUILD_TYPE=Release" >> $GITHUB_ENV
      echo "CMAKE_CONFIG_PRESET=conan-release" >> $GITHUB_ENV
      echo "CMAKE_BUILD_PRESET=conan-release" >> $GITHUB_ENV
      echo "CMAKE_TEST_PRESET=conan-release" >> $GITHUB_ENV

  - name: Install deps
    env:
      CONAN_PROFILE: conan/profiles/ci/${{ inputs.compiler }}
    shell: bash
    run: >
      conan install ./conanfile.py
      --profile:host=${{ env.CONAN_PROFILE }}
      --profile:build=${{ env.CONAN_PROFILE }}
      --settings=build_type=${{ env.BUILD_TYPE }}
      --build=missing

  - name: Configure
    shell: bash
    run: cmake --preset ${{ env.CMAKE_CONFIG_PRESET }}

  - name: Build
    shell: bash
    run: cmake --build --preset ${{ env.CMAKE_BUILD_PRESET }}

  - name: Run tests
    shell: bash
    run: ctest --preset ${{ env.CMAKE_TEST_PRESET }}
