name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [msvc, clang, gcc]
        include:
          - os: windows-latest
            compiler: msvc
          - os: ubuntu-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: clang
        exclude:
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang
          - os: ubuntu-latest
            compiler: msvc

    steps:
    - uses: actions/checkout@v3

    - name: Setup env (Ubuntu)
      if: ${{ matrix.compiler == 'gcc' }}
      run: |
        echo "CC=gcc-13" >> $GITHUB_ENV
        echo "CXX=g++-13" >> $GITHUB_ENV

    - name: Cache LLVM
      if: ${{ matrix.compiler == 'clang' }}
      id: cache-llvm
      uses: actions/cache@v3
      with:
        path: |
          ./llvm
        key: llvm-16

    - name: Install and configure compiler (Clang)
      if: ${{ matrix.compiler == 'clang' }}
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "16.0"
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
        env: true

    - name: Configure compiler (GCC)
      if: ${{ matrix.compiler == 'gcc' }}
      run: |
        echo "CC=gcc-13" >> $GITHUB_ENV
        echo "CXX=g++-13" >> $GITHUB_ENV

    - name: Configure runner
      run: |
        pip install conan
        conan --version
        conan profile detect --force

    - name: Install deps
      run: >
        conan install ${{ github.workspace }}/conanfile.py
        --profile:host=${{ github.workspace }}/conan/profiles/ci/${{ matrix.compiler }}
        --profile:build=${{ github.workspace }}/conan/profiles/ci/${{ matrix.compiler }}
        --settings=build_type=Release
        --build=missing

    - name: Configure
      run: cmake --preset conan-release

    - name: Build
      run: cmake --build --preset conan-release
