name: apple-clang-15/macos-13

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_run_tests:
    runs-on: [macos-13]

    env:
      DEVELOPER_DIR: /Applications/Xcode_15.0.1.app/Contents/Developer

    steps:
    - uses: actions/checkout@v3

    - name: Configure runner
      shell: bash
      run: |
        pip3 install conan
        conan --version
        conan profile detect --force

    - name: Run tests
      uses: ./.github/actions/run_tests
      with:
        compiler: "apple-clang"

