name: msvc-19.3/windows-2022

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_run_tests:
    runs-on: [windows-2022]

    env:
      COMPILER: msvc-19.3

    steps:
    - uses: actions/checkout@v3

    - name: Run tests
      uses: ./.github/actions/run_tests
      with:
        compiler: ${{ env.COMPILER }}

