name: clang-16/ubuntu-22.04

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_run_tests:
    runs-on: [ubuntu-22.04]

    env:
      LLVM_VERSION: 16.0
      COMPILER: clang-16

    steps:
    - uses: actions/checkout@v3

    - name: Cache LLVM
      id: cache-llvm
      uses: actions/cache@v3
      with:
        path: |
          ./llvm
        key: ${{ runner.os }}-${{ runner.arch }}__llvm-${{ env.LLVM_VERSION }}

    - name: Install and configure compiler
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: ${{ env.LLVM_VERSION }}
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
        env: true

    - name: Run tests
      uses: ./.github/actions/run_tests
      with:
        compiler: ${{ env.COMPILER }}
