name: gcc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_run_tests:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Configure compiler
      shell: bash
      run: |
        echo "CC=gcc-13" >> $GITHUB_ENV
        echo "CXX=g++-13" >> $GITHUB_ENV

    - name: Configure runner
      shell: bash
      run: |
        pip install conan
        conan --version
        conan profile detect --force

    - name: Run tests
      uses: ./.github/actions/run_tests
      with:
        compiler: "gcc"
