name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [msvc, clang, gcc]
        include:
          - os: windows-latest
            compiler: msvc
          - os: ubuntu-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: clang
        exclude:
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang
          - os: ubuntu-latest
            compiler: msvc

    steps:
    - uses: actions/checkout@v3

    - name: Setup env (Clang)
      if: ${{ matrix.compiler == 'clang' }}
      run: |
        echo "CC=clang-16" >> $GITHUB_ENV
        echo "CXX=clang++-16" >> $GITHUB_ENV

    - name: Setup env (GCC)
      if: ${{ matrix.compiler == 'gcc' }}
      run: |
        echo "CC=gcc-13" >> $GITHUB_ENV
        echo "CXX=g++-13" >> $GITHUB_ENV

    - name: Configure runner
      run: |
        pip install conan
        conan --version
        conan profile detect --force

    - name: Install deps (Debug)
      run: >
        conan install ${{ github.workspace }}/conanfile.py
        --profile:host=${{ github.workspace }}/conan/profiles/ci/${{ matrix.compiler }}
        --profile:build=${{ github.workspace }}/conan/profiles/ci/${{ matrix.compiler }}
        --settings=build_type=Debug
        --build=missing

    - name: Install deps (Release)
      run: >
        conan install ${{ github.workspace }}/conanfile.py
        --profile:host=${{ github.workspace }}/conan/profiles/ci/${{ matrix.compiler }}
        --profile:build=${{ github.workspace }}/conan/profiles/ci/${{ matrix.compiler }}
        --settings=build_type=Release
        --build=missing

    - name: Configure
      run: cmake --preset release

    - name: Build
      run: cmake --build --preset release
