name: apple-clang-15/macos-13

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_run_tests:
    runs-on: [macos-13]

    env:
      DEVELOPER_DIR: /Applications/Xcode_15.0.1.app/Contents/Developer
      CONAN_VERSION: 2.0.14

    steps:
    - uses: actions/checkout@v3

    - name: Install pipx packages
      shell: bash
      run: |
        pipx install conan==${{ env.CONAN_VERSION }}

    - name: Configure conan
      shell: bash
      run: |
        conan --version
        conan profile detect --force --name base
        cp conan/profiles/apple-clang-15 $(dirname $(conan profile path base))/default

    - name: Run tests
      uses: ./.github/actions/run_tests

