name: validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: [ubuntu-22.04]

    env:
      LLVM_VERSION: "16.0.6"

    steps:
    - uses: actions/checkout@v3

    - name: Configure compiler & tools
      uses: aminya/setup-cpp@v1
      with:
        compiler: llvm-${{ env.LLVM_VERSION }}
        clangtidy: ${{ env.LLVM_VERSION }}
        clangformat: ${{ env.LLVM_VERSION }}
        cppcheck: true
        make: true
        cmake: true
        ninja: true

    - name: Configure conan
      shell: bash
      run: |
        pip install conan
        conan --version
        conan profile detect --force
        sed -i 's/libstdc++.*/libc++/' ~/.conan2/profiles/default

    - name: Configure tools
      shell: bash
      run: |
        pip install cpplint
        cpplint --version
        cppcheck --version
        clang-tidy --version
        clang-format --version

    - name: Run tests
      shell: bash
      run: make -k validate

