name: validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_run_tests:
    runs-on: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@v3

    - name: Configure runner
      uses: aminya/setup-cpp@v1
      with:
        compiler: llvm-16.0.6
        clangtidy: 16.0.6
        clangformat: 16.0.6
        cppcheck: true
        conan: 2.0.13
        make: true
        cmake: true
        ninja: true

    - name: Configure conan
      shell: bash
      run: |
        conan --version
        conan profile detect --force

    - name: Run tests
      shell: bash
      run: make build validate

