name: validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: [ubuntu-22.04]

    env:
      LLVM_VERSION: "17.0.5"

    steps:
    - uses: actions/checkout@v3

    - name: Configure runner
      uses: aminya/setup-cpp@v1
      with:
        compiler: llvm-${{ env.LLVM_VERSION }}
        clangtidy: ${{ env.LLVM_VERSION }}
        clangformat: ${{ env.LLVM_VERSION }}
        cppcheck: 2.12.1
        conan: 2.0.13
        make: true
        cmake: true
        ninja: true

    - name: Configure conan
      shell: bash
      run: |
        conan --version
        conan profile detect --force

    - name: Run tests
      shell: bash
      run: make -k validate

