name: validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_run_tests:
    runs-on: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@v3

    - name: Configure runner
      uses: aminya/setup-cpp@v1
      with:
        compiler: llvm-16.0.6
        cmake: true
        conan: true
        cppcheck: true
        clangtidy: true
        clangformat: "15.0.7"

    - name: Configure conan
      shell: bash
      run: |
        conan --version
        conan profile detect --force

    - name: Run tests
      shell: bash
      run: make init

