name: validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: [ubuntu-22.04]

    env:
      LLVM_VERSION: "16.0"

    steps:
    - uses: actions/checkout@v3

    - name: Cache LLVM
      id: cache-llvm
      uses: actions/cache@v3
      with:
        path: |
          ./llvm
        key: llvm-${{ env.LLVM_VERSION }}

    - name: Install and configure tools
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install cppcheck
        sudo apt-get install ninja-build
        sudo apt-get install iwyu

        pipx install conan
        pipx install cpplint
        pipx install clang-format==16.0.6
        pipx install clang-tidy==17.0.1
        pipx ensurepath
        echo $(pipx environment --value PIPX_BIN_DIR) >> $GITHUB_PATH

        pipx environment --value PIPX_BIN_DIR
        cat $GITHUB_PATH
        echo $PATH

    - name: Install and configure compiler
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: ${{ env.LLVM_VERSION }}
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
        env: true

    - name: Configure conan
      shell: bash
      run: |
        conan profile detect --force --name base
        cp conan/profiles/clang-16 $(dirname $(conan profile path base))/default

    - name: Validate
      shell: bash
      run: |
        cat $GITHUB_PATH
        echo $PATH

        conan --version
        cpplint --version
        cppcheck --version
        clang-tidy --version
        clang-format --version

        make -k validate

