name: validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: [ubuntu-22.04]

    env:
      LLVM_VERSION: "16.0"

    steps:
    - uses: actions/checkout@v3

    - name: Cache LLVM
      id: cache-llvm
      uses: actions/cache@v3
      with:
        path: |
          ./llvm
        key: ${{ runner.os }}-${{ runner.arch }}__llvm-${{ env.LLVM_VERSION }}

    - name: Install and configure compiler
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: ${{ env.LLVM_VERSION }}
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
        env: true

    - name: Install pipx packages
      shell: bash
      run: |
        pipx install conan
        pipx install cpplint
        pipx install clang-format==16.0.6
        pipx install clang-tidy==17.0.1
        echo $(pipx environment --value PIPX_BIN_DIR) >> $GITHUB_PATH

    - name: Configure conan
      shell: bash
      run: |
        conan profile detect --force --name base
        cp conan/profiles/clang-16 $(dirname $(conan profile path base))/default

    - name: Install conan packages
      shell: bash
      run: |
        conan install \
          --tool-requires "cmake/3.27.7" \
          --tool-requires "ninja/1.11.1" \
          --tool-requires "cppcheck/2.12.1" \
          --output-folder=./pkgs \
          --build=missing

    - name: Validate
      shell: bash
      run: |
        source ./pkgs/conanbuild.sh
        make -k validate

