name: validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: [ubuntu-22.04]

    env:
      LLVM_VERSION: 16.0
      CONAN_VERSION: 2.0.14
      CLANG_FORMAT_VERSION: 16.0.6
      CLANG_TIDY_VERSION: 17.0.1

    steps:
    - uses: actions/checkout@v3

    - name: Cache LLVM
      id: cache-llvm
      uses: actions/cache@v3
      with:
        path: |
          ./llvm
        key: ${{ runner.os }}-${{ runner.arch }}__llvm-${{ env.LLVM_VERSION }}

    - name: Install and configure compiler
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: ${{ env.LLVM_VERSION }}
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
        env: true

    - name: Install pipx packages
      shell: bash
      run: |
        pipx install conan==${{ env.CONAN_VERSION }}
        pipx install cpplint
        pipx install clang-format==${{ env.CLANG_FORMAT_VERSION }}
        pipx install clang-tidy==${{ env.CLANG_TIDY_VERSION }}
        pipx environment --value PIPX_BIN_DIR >> $GITHUB_PATH

    - name: Configure conan
      shell: bash
      run: |
        conan profile detect --force --name base
        cp conan/profiles/clang-16 $(dirname $(conan profile path base))/default

    - name: Restore conan cache
      id: cache-conan
      uses: ./.github/actions/conan_cache/restore
      with:
        key: ${{ runner.os }}-${{ runner.arch }}__conan-${{ env.CONAN_VERSION }}__${{ hashFiles('./.github/workflows/cfg/tools_conanfile.txt', './conanfile.py') }}

    - name: Install conan packages
      shell: bash
      run: |
        conan install ./.github/workflows/cfg/tools_conanfile.txt \
          --output-folder=./pkgs \
          --build=missing

    - name: Validate
      shell: bash
      run: |
        source ./pkgs/conanbuild.sh
        make -k validate

    - name: Save conan cache
      if: ${{ !steps.cache-conan.outputs.cache-hit }}
      uses: ./.github/actions/conan_cache/save
      with:
        key: ${{ steps.cache-conan.outputs.cache-primary-key }}

